---
title: "Week1 Assignment Question 2"
author: ""
date: "December 19, 2016"
output: pdf_document
geometry: margin=1.5cm
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'pdf')
```

# Question 2

Make a plot (possibly multi-panel) that answers the question: how does the relationship between mean covered charges (Average.Covered.Charges) and mean total payments (Average.Total.Payments) vary by medical condition (DRG.Definition) and the state in which care was received (Provider.State)?

## 1. Load Data

```{r}
mypath <- "./data/week1_payments.csv"
mydf <- read.csv(mypath)
dim(mydf)
names(mydf)
```

## 2. Check Data

```{r}
summary(mydf$DRG.Definition)
summary(mydf$Provider.State)
```

## 3. Plot

```{r, fig.width=18, fig.height=15}
state.levels <- levels(mydf$Provider.State)
drg.levels <- levels(mydf$DRG.Definition)
drg.num <- length(drg.levels)
cols <- rainbow(length(drg.levels))

layout(matrix(c(1,2,3,4,5,6,7,7,7), 3, 3, byrow = TRUE))
for (i in state.levels) {
    par(new)
    mydf3 <- mydf[mydf$Provider.State == i, ]
    plot(mydf3$Average.Covered.Charges,
         mydf3$Average.Total.Payments,
         pch = 19,
         col = cols,
         main = i,
         xlab = "Mean Covered Charges",
         ylab = "Mean Total Payments")
    for (j in 1:drg.num) {
        abline(lm(data = mydf3[mydf3$DRG.Definition == drg.levels[j], ],
                  formula = Average.Total.Payments~Average.Covered.Charges),
               col = cols[j])
    }
}

plot.new()
title(main = list("Plot 2: Relationship between Mean Covered Charges and Mean Total Payments 
                   Vary by Medical Condition and the State",
                  cex = 4, col = "black", font = 1),
      line = -4)
legend("center", ncol = 2,
       legend = levels(mydf$DRG.Definition),
       cex = 1.5, 
       fill = cols,
       title = "Medical Conditions")
```



