---
title: "Week 1 Assignment Question 1"
author: ""
date: "December 19, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 1

Make a plot that answers the question: what is the relationship between mean covered charges (Average.Covered.Charges) and mean total payments (Average.Total.Payments) in New York?

## 1. Load Data

```{r mydf}
mypath <- "./data/week1_payments.csv"
mydf <- read.csv(mypath)
dim(mydf)
names(mydf)
```

## 2. Subset Data

```{r}
summary(mydf$Provider.State)
mydf2 <- mydf[mydf$Provider.State == "NY", ]
dim(mydf2)
```

## 3. Plot

```{r}
plot(mydf2$Average.Covered.Charges, mydf2$Average.Total.Payments, 
     pch = 1, cex = 0.5,
     main = "Plot 1 Relationship between Mean Covered Charges
             and Mean Total Payments in New York",
     xlab = "Mean Covered Charges",
     ylab = "Mean Total Payments")
abline(lm(data = mydf2,
          formula = Average.Total.Payments~Average.Covered.Charges),
       col = "green")
```
